version: '3.1'

services:

  wordpress:
    depends_on:
      - db
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: mysql_user
      WORDPRESS_DB_PASSWORD: Qwerty12345
      WORDPRESS_DB_NAME: estatedb
    volumes:
      - ./:/var/www/html

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: estatedb
      MYSQL_USER: mysql_user
      MYSQL_PASSWORD: Qwerty12345
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db: